name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23litOCjakjjtVb297"
GITHUB_OWNER = "sc1entist"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "cloudflare"
NEXTAUTH_URL = "https://navsphere-1zv.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-1zv.pages.dev/"
